/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CadastroFornecedor.java
 *
 * Created on 01/02/2013, 17:29:05
 */
package br.com.chronos.vetfaunasistema.view.fornecedor;

import br.com.chronos.vetfaunasistema.view.generic.CrudView;
import br.com.chronos.vetfaunasistema.view.main.TelaPrincipal;
import javax.swing.JInternalFrame;

/**
 *
 * @author Fernando
 */
public class CadastroFornecedor extends JInternalFrame implements CrudView {

    private FornecedorPanel fornecedorPanel;

    /** Creates new form CadastroFornecedor */
    public CadastroFornecedor(TelaPrincipal telaPrincipal) {
        fornecedorPanel = new FornecedorPanel(this,telaPrincipal);
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = fornecedorPanel;

        setTitle("Cadastro de Fornecedor");
        getContentPane().setLayout(null);
        getContentPane().add(pnlPrincipal);
        pnlPrincipal.setBounds(0, 0, 546, 503);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-565)/2, (screenSize.height-535)/2, 565, 535);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables

    public void setVisible(boolean valor) {
        if (valor) {
            fornecedorPanel.setVisible(valor);
        }
        super.setVisible(valor);
    }
}
