/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FornecedorPanel.java
 *
 * Created on 13/02/2013, 17:59:49
 */
package br.com.chronos.vetfaunasistema.view.fornecedor;

import br.com.chronos.vetfaunasistema.business.fornecedor.FornecedorBusiness;
import br.com.chronos.vetfaunasistema.business.fornecedor.FornecedorBusinessImpl;
import br.com.chronos.vetfaunasistema.domain.Fornecedor;
import br.com.chronos.vetfaunasistema.utilitarios.enums.TypeMask;
import br.com.chronos.vetfaunasistema.view.generic.ContactJPanel;
import br.com.chronos.vetfaunasistema.view.generic.CrudView;
import br.com.chronos.vetfaunasistema.view.generic.GenericViewCrud;
import br.com.chronos.vetfaunasistema.view.component.jformatter.MaxLengthTextDocument;
import br.com.chronos.vetfaunasistema.view.component.table.MyTable;
import br.com.chronos.vetfaunasistema.view.main.TelaPrincipal;
import java.awt.event.KeyEvent;
import javax.swing.JButton;

/**
 *
 * @author Fernando
 */
public class FornecedorPanel extends GenericViewCrud<Fornecedor, FornecedorBusiness> {

    private Fornecedor fornecedor;
    private Fornecedor fornecedorPesquisa;
    private FornecedorBusiness fornecedorBusiness;
    private ContactJPanel contactJPanel;

    /** Creates new form FornecedorPanel */
    public FornecedorPanel(CrudView crudView,TelaPrincipal telaPrincipal) {
        setCrudView(crudView);
        setTelaPrincipal(telaPrincipal);
        fornecedor = new Fornecedor();
        fornecedorPesquisa = new Fornecedor();
        contactJPanel = new ContactJPanel();
        instanceFornecedorBusiness();
        initComponents();
        actions();
    }

    private FornecedorBusiness instanceFornecedorBusiness() {
        if (fornecedorBusiness == null) {
            fornecedorBusiness = new FornecedorBusinessImpl();
        }
        return fornecedorBusiness;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFornecedor = getMyTable();
        jLabel14 = new javax.swing.JLabel();
        txtNomeFornecedorPesquisa = new javax.swing.JTextField();
        btnPesquisa = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNomeFornecedor = new javax.swing.JTextField();
        btnNovo = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        pnlContato = contactJPanel;
        btnFechar = new javax.swing.JButton();

        setLayout(null);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa"));
        jPanel6.setLayout(null);

        tblFornecedor.setModel(getMyTable().getModel());
        jScrollPane2.setViewportView(tblFornecedor);

        jPanel6.add(jScrollPane2);
        jScrollPane2.setBounds(10, 60, 530, 130);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLabel14.setText("Nome:");
        jPanel6.add(jLabel14);
        jLabel14.setBounds(20, 20, 50, 20);

        txtNomeFornecedorPesquisa.setFont(new java.awt.Font("Tahoma", 0, 10));
        txtNomeFornecedorPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeFornecedorPesquisaKeyPressed(evt);
            }
        });
        jPanel6.add(txtNomeFornecedorPesquisa);
        txtNomeFornecedorPesquisa.setBounds(60, 20, 260, 23);

        btnPesquisa.setText("Pesquisar");
        jPanel6.add(btnPesquisa);
        btnPesquisa.setBounds(330, 20, 90, 23);

        add(jPanel6);
        jPanel6.setBounds(0, 0, 550, 200);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Pessoais"));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setText("Nome do Fornecedor: ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(12, 27, 110, 13);

        txtNomeFornecedor.setDocument(new MaxLengthTextDocument(TypeMask.TEXT, 149, ""));
        txtNomeFornecedor.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtNomeFornecedor.setEnabled(false);
        jPanel1.add(txtNomeFornecedor);
        txtNomeFornecedor.setBounds(12, 40, 280, 23);

        btnNovo.setText("Novo");
        jPanel1.add(btnNovo);
        btnNovo.setBounds(80, 230, 73, 23);

        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        jPanel1.add(btnAlterar);
        btnAlterar.setBounds(160, 230, 65, 23);

        btnSalvar.setText("Salvar");
        btnSalvar.setEnabled(false);
        jPanel1.add(btnSalvar);
        btnSalvar.setBounds(230, 230, 70, 23);

        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        jPanel1.add(btnExcluir);
        btnExcluir.setBounds(305, 230, 70, 23);

        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        jPanel1.add(btnCancelar);
        btnCancelar.setBounds(380, 230, 80, 23);

        pnlContato.setLayout(null);
        jPanel1.add(pnlContato);
        pnlContato.setBounds(10, 70, 520, 150);

        add(jPanel1);
        jPanel1.setBounds(0, 200, 550, 270);

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        add(btnFechar);
        btnFechar.setBounds(430, 470, 80, 23);
    }// </editor-fold>//GEN-END:initComponents

private void txtNomeFornecedorPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeFornecedorPesquisaKeyPressed
    int key = evt.getKeyCode();
    if (key == KeyEvent.VK_ENTER) {
        setStatusPesquisar();
    }
}//GEN-LAST:event_txtNomeFornecedorPesquisaKeyPressed

private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
    setVisible(false);
    txtNomeFornecedorPesquisa.setText("");
}//GEN-LAST:event_btnFecharActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlContato;
    private javax.swing.JTable tblFornecedor;
    private javax.swing.JTextField txtNomeFornecedor;
    private javax.swing.JTextField txtNomeFornecedorPesquisa;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setEnabledObjctes(boolean valor) {
        txtNomeFornecedor.setEnabled(valor);
        contactJPanel.setEnabled(valor);
    }

    @Override
    public void setEmptyObjects() {
        txtNomeFornecedor.setText("");
        contactJPanel.setEmptyObjects();
    }

    @Override
    public Fornecedor getGenericPesquisaDomain() {
        fornecedorPesquisa.setNome(txtNomeFornecedorPesquisa.getText());
        return fornecedorPesquisa;
    }

    @Override
    protected Fornecedor getEntidade() {
        fornecedor.setNome(txtNomeFornecedor.getText());
        fornecedor.setTelefoneContato(contactJPanel.getListOriginal());
        return fornecedor;
    }

    @Override
    protected void setEntidade(Fornecedor entidade) {
        fornecedor = (Fornecedor) entidade;
        txtNomeFornecedor.setText(fornecedor.getNome());
        contactJPanel.setTableValue(fornecedor.getTelefoneContato());
    }

    @Override
    public FornecedorBusiness getGenericBusiness() {
        return instanceFornecedorBusiness();
    }

    @Override
    public JButton getBtnSalvar() {
        return btnSalvar;
    }

    @Override
    public JButton getBtnExcluir() {
        return btnExcluir;
    }

    @Override
    public JButton getBtnAlterar() {
        return btnAlterar;
    }

    @Override
    public JButton getBtnPesquisar() {
        return btnPesquisa;
    }

    @Override
    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    @Override
    public JButton getBtnNovo() {
        return btnNovo;
    }

    @Override
    public void setTable(MyTable myTable) {
        tblFornecedor = myTable;
    }
}
