/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FuncionarioPanel.java
 *
 * Created on 13/02/2013, 16:55:53
 */
package br.com.chronos.vetfaunasistema.view.funcionario;

import br.com.chronos.vetfaunasistema.business.cargo.CargoBusiness;
import br.com.chronos.vetfaunasistema.business.cargo.CargoBusinessImpl;
import br.com.chronos.vetfaunasistema.business.cargo.exception.CargoBusinessException;
import br.com.chronos.vetfaunasistema.business.funcionario.FuncionarioBusiness;
import br.com.chronos.vetfaunasistema.business.funcionario.FuncionarioBusinessImpl;
import br.com.chronos.vetfaunasistema.domain.Cargo;
import br.com.chronos.vetfaunasistema.domain.Funcionario;
import br.com.chronos.vetfaunasistema.utilitarios.enums.TypeMask;
import br.com.chronos.vetfaunasistema.utilitarios.util.Util;
import br.com.chronos.vetfaunasistema.view.generic.ContactJPanel;
import br.com.chronos.vetfaunasistema.view.generic.CrudView;
import br.com.chronos.vetfaunasistema.view.generic.GenericViewCrud;
import br.com.chronos.vetfaunasistema.view.component.jformatter.MaxLengthTextDocument;
import br.com.chronos.vetfaunasistema.view.component.jformatter.NumberJFormatter;
import br.com.chronos.vetfaunasistema.view.component.table.MyTable;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Fernando
 */
public class FuncionarioPanel extends GenericViewCrud<Funcionario, FuncionarioBusiness> {

    private Funcionario funcionario;
    private Funcionario funcionarioPesquisa;
    private FuncionarioBusiness funcionarioBusiness;
    private NumberFormat formatoMoeda = DecimalFormat.getInstance();
    private SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
    private List<Cargo> listaCargo;
    private CargoBusiness cargoBusiness;
    private ContactJPanel contactJPanel;
    private final Cargo primeiroCargo = new Cargo("--Selecione uma opção--");

    /** Creates new form FuncionarioPanel */
    public FuncionarioPanel(CrudView crudView) {
        setCrudView(crudView);
        funcionario = new Funcionario();
        funcionarioPesquisa = new Funcionario();
        contactJPanel = new ContactJPanel();
        instanceFuncionarioBusiness();
        instanceCargoBusiness();
        initComponents();
        preencheCargo();
        actions();
    }

    protected Component[] getRepaintComponets(){
        return new Component[]{cmbCargo};
    }
    
    private void preencheCargo() {
        try {
            listaCargo = cargoBusiness.select(new Cargo());
            cmbCargo.removeAllItems();
            cmbCargo.addItem(primeiroCargo);
            for (Cargo cargo : listaCargo) {
                cmbCargo.addItem(cargo);
            }
        } catch (CargoBusinessException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", 0);
        }
    }

    private FuncionarioBusiness instanceFuncionarioBusiness() {
        if (funcionarioBusiness == null) {
            funcionarioBusiness = new FuncionarioBusinessImpl();
        }
        return funcionarioBusiness;
    }

    private void instanceCargoBusiness() {
        if (cargoBusiness == null) {
            cargoBusiness = new CargoBusinessImpl();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNomeFuncionario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCpf = new br.com.chronos.vetfaunasistema.view.component.jformatter.NumberJFormatter(br.com.chronos.vetfaunasistema.utilitarios.enums.TypeMask.CPF,14,"");
        txtDataNascimento = new NumberJFormatter(br.com.chronos.vetfaunasistema.utilitarios.enums.TypeMask.DATA,10,"");
        txtRg = new NumberJFormatter(br.com.chronos.vetfaunasistema.utilitarios.enums.TypeMask.INTEGER,20,"");
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbCargo = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtDataContratacao = new NumberJFormatter(br.com.chronos.vetfaunasistema.utilitarios.enums.TypeMask.DATA,10,"");
        txtClt = new NumberJFormatter(br.com.chronos.vetfaunasistema.utilitarios.enums.TypeMask.INTEGER,20,"");
        txtPis = new NumberJFormatter(br.com.chronos.vetfaunasistema.utilitarios.enums.TypeMask.PIS,14,"");
        txtDiaPagamento = new NumberJFormatter(br.com.chronos.vetfaunasistema.utilitarios.enums.TypeMask.INTEGER,2,"0");
        txtSalario = new br.com.chronos.vetfaunasistema.view.component.jformatter.NumberJFormatter(br.com.chronos.vetfaunasistema.utilitarios.enums.TypeMask.DECIMAL,9,"0,00");
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        pnlContato = contactJPanel;
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFuncionario = getMyTable();
        jLabel14 = new javax.swing.JLabel();
        txtNomeFuncionarioPesquisa = new javax.swing.JTextField();
        btnPesquisa = new javax.swing.JButton();

        setLayout(null);

        jButton4.setText("Fechar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4);
        jButton4.setBounds(540, 620, 80, 23);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro"));
        jPanel1.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Pessoais"));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLabel1.setText("Nome do Funcionário: ");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(12, 27, 110, 13);

        txtNomeFuncionario.setDocument(new MaxLengthTextDocument(TypeMask.TEXT, 149, ""));
        txtNomeFuncionario.setFont(new java.awt.Font("Tahoma", 0, 10));
        txtNomeFuncionario.setEnabled(false);
        jPanel2.add(txtNomeFuncionario);
        txtNomeFuncionario.setBounds(12, 40, 280, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLabel2.setText("Data Nascimento:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(12, 114, 110, 13);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLabel4.setText("CPF:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(176, 70, 23, 13);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLabel5.setText("Rg:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(12, 70, 16, 13);

        txtCpf.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCpf.setEnabled(false);
        txtCpf.setFont(new java.awt.Font("Tahoma", 0, 10));
        jPanel2.add(txtCpf);
        txtCpf.setBounds(176, 84, 115, 23);

        txtDataNascimento.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDataNascimento.setEnabled(false);
        txtDataNascimento.setFont(new java.awt.Font("Tahoma", 0, 10));
        jPanel2.add(txtDataNascimento);
        txtDataNascimento.setBounds(12, 126, 140, 22);

        txtRg.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtRg.setEnabled(false);
        txtRg.setFont(new java.awt.Font("Tahoma", 0, 10));
        jPanel2.add(txtRg);
        txtRg.setBounds(12, 84, 140, 22);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 30, 300, 170);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Trabalhistas"));
        jPanel3.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLabel6.setText("Data Contratação:");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(170, 27, 110, 13);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLabel3.setText("Cargo:");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(12, 27, 70, 13);

        cmbCargo.setFont(new java.awt.Font("Tahoma", 0, 10));
        cmbCargo.setEnabled(false);
        jPanel3.add(cmbCargo);
        cmbCargo.setBounds(12, 40, 140, 23);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel7.setText("Número CLT:");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(12, 70, 80, 13);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLabel8.setText("Pis:");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(170, 70, 120, 13);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLabel9.setText("Dia Pagamento:");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(12, 114, 80, 13);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLabel10.setText("Salário:");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(170, 114, 50, 13);

        txtDataContratacao.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDataContratacao.setEnabled(false);
        txtDataContratacao.setFont(new java.awt.Font("Tahoma", 0, 10));
        jPanel3.add(txtDataContratacao);
        txtDataContratacao.setBounds(170, 40, 130, 22);

        txtClt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtClt.setEnabled(false);
        txtClt.setFont(new java.awt.Font("Tahoma", 0, 10));
        jPanel3.add(txtClt);
        txtClt.setBounds(12, 84, 140, 22);

        txtPis.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPis.setEnabled(false);
        txtPis.setFont(new java.awt.Font("Tahoma", 0, 10));
        jPanel3.add(txtPis);
        txtPis.setBounds(170, 84, 130, 22);

        txtDiaPagamento.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDiaPagamento.setEnabled(false);
        txtDiaPagamento.setFont(new java.awt.Font("Tahoma", 0, 10));
        jPanel3.add(txtDiaPagamento);
        txtDiaPagamento.setBounds(12, 126, 50, 22);

        txtSalario.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSalario.setEnabled(false);
        txtSalario.setFont(new java.awt.Font("Tahoma", 0, 10));
        jPanel3.add(txtSalario);
        txtSalario.setBounds(170, 126, 130, 23);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(310, 30, 320, 170);

        btnNovo.setText("Novo");
        jPanel1.add(btnNovo);
        btnNovo.setBounds(110, 360, 73, 23);

        btnSalvar.setText("Salvar");
        btnSalvar.setEnabled(false);
        jPanel1.add(btnSalvar);
        btnSalvar.setBounds(260, 360, 70, 23);

        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        jPanel1.add(btnAlterar);
        btnAlterar.setBounds(190, 360, 65, 23);

        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        jPanel1.add(btnCancelar);
        btnCancelar.setBounds(410, 360, 80, 23);

        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        jPanel1.add(btnExcluir);
        btnExcluir.setBounds(335, 360, 70, 23);

        pnlContato.setLayout(null);
        jPanel1.add(pnlContato);
        pnlContato.setBounds(50, 200, 530, 150);

        add(jPanel1);
        jPanel1.setBounds(0, 220, 640, 400);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa"));
        jPanel6.setLayout(null);

        tblFuncionario.setModel(getMyTable().getModel());
        jScrollPane2.setViewportView(tblFuncionario);

        jPanel6.add(jScrollPane2);
        jScrollPane2.setBounds(10, 60, 620, 130);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLabel14.setText("Nome:");
        jPanel6.add(jLabel14);
        jLabel14.setBounds(20, 20, 50, 20);

        txtNomeFuncionarioPesquisa.setFont(new java.awt.Font("Tahoma", 0, 10));
        txtNomeFuncionarioPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeFuncionarioPesquisaKeyPressed(evt);
            }
        });
        jPanel6.add(txtNomeFuncionarioPesquisa);
        txtNomeFuncionarioPesquisa.setBounds(60, 20, 260, 23);

        btnPesquisa.setText("Pesquisar");
        jPanel6.add(btnPesquisa);
        btnPesquisa.setBounds(330, 20, 90, 23);

        add(jPanel6);
        jPanel6.setBounds(0, 0, 640, 220);
    }// </editor-fold>//GEN-END:initComponents

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    setVisible(false);
    txtNomeFuncionarioPesquisa.setText("");
}//GEN-LAST:event_jButton4ActionPerformed

private void txtNomeFuncionarioPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeFuncionarioPesquisaKeyPressed
    int key = evt.getKeyCode();
    if (key == KeyEvent.VK_ENTER) {
        setStatusPesquisar();
    }
}//GEN-LAST:event_txtNomeFuncionarioPesquisaKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cmbCargo;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlContato;
    private javax.swing.JTable tblFuncionario;
    private javax.swing.JFormattedTextField txtClt;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JFormattedTextField txtDataContratacao;
    private javax.swing.JFormattedTextField txtDataNascimento;
    private javax.swing.JFormattedTextField txtDiaPagamento;
    private javax.swing.JTextField txtNomeFuncionario;
    private javax.swing.JTextField txtNomeFuncionarioPesquisa;
    private javax.swing.JFormattedTextField txtPis;
    private javax.swing.JFormattedTextField txtRg;
    private javax.swing.JFormattedTextField txtSalario;
    // End of variables declaration//GEN-END:variables

    private BigDecimal getSalario() throws ParseException {
        if (txtSalario.getText().isEmpty() || txtSalario.getText().equals("0,00")) {
            return null;
        } else {
            return new BigDecimal("" + formatoMoeda.parse(txtSalario.getText()));
        }

    }

    private Date getDataNascimento() throws ParseException {
        if (txtDataNascimento.getText().equals("")) {
            return null;
        } else {
            return formato.parse(txtDataNascimento.getText());
        }

    }

    private Date getDataContratacao() throws ParseException {
        if (txtDataContratacao.getText().equals("")) {
            return null;
        } else {
            return formato.parse(txtDataContratacao.getText());
        }

    }

    private Cargo getCargo() {
        if (cmbCargo.getSelectedIndex() > 0) {
            return (Cargo) cmbCargo.getSelectedItem();
        } else {
            return null;
        }
    }

    @Override
    protected Funcionario getEntidade() {
        try {
            funcionario.setNome(txtNomeFuncionario.getText());
            funcionario.setCarteiraTrabalho(txtClt.getText());
            funcionario.setCpf(Util.returnNullIfEmpty(txtCpf.getText().replace(".", "").replace("-", "")));
            funcionario.setPis(Util.returnNullIfEmpty(txtPis.getText().replace(".", "").replace("-", "")));
            funcionario.setRg(Util.returnNullIfEmpty(txtRg.getText()));
            funcionario.setCargo(getCargo());
            funcionario.setDataContratacao(getDataContratacao());
            funcionario.setDataNascimento(getDataNascimento());
            funcionario.setDiaPagamento(Integer.parseInt(txtDiaPagamento.getText().trim()));
            funcionario.setSalario(getSalario());
            funcionario.setTelefoneContato(contactJPanel.getListOriginal());
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao converter valor.", "Erro", 0);
        }
        return funcionario;
    }

    @Override
    public void setEnabledObjctes(boolean valor) {
        txtClt.setEnabled(valor);
        txtCpf.setEnabled(valor);
        txtDataContratacao.setEnabled(valor);
        txtDataNascimento.setEnabled(valor);
        txtDiaPagamento.setEnabled(valor);
        txtNomeFuncionario.setEnabled(valor);
        txtPis.setEnabled(valor);
        txtRg.setEnabled(valor);
        txtSalario.setEnabled(valor);
        cmbCargo.setEnabled(valor);
        contactJPanel.setEnabled(valor);
    }

    @Override
    public void setEmptyObjects() {
        txtClt.setText("");
        txtCpf.setText("");
        txtDataContratacao.setText("");
        txtDataNascimento.setText("");
        txtDiaPagamento.setText("");
        txtNomeFuncionario.setText("");
        txtPis.setText("");
        txtRg.setText("");
        txtSalario.setText("");
        cmbCargo.setSelectedIndex(0);
        contactJPanel.setEmptyObjects();
    }

    @Override
    public JButton getBtnSalvar() {
        return btnSalvar;
    }

    @Override
    public JButton getBtnExcluir() {
        return btnExcluir;
    }

    @Override
    public JButton getBtnAlterar() {
        return btnAlterar;
    }

    @Override
    public JButton getBtnPesquisar() {
        return btnPesquisa;
    }

    @Override
    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    @Override
    public JButton getBtnNovo() {
        return btnNovo;
    }

    @Override
    public void setTable(MyTable myTable) {
        tblFuncionario = myTable;
    }

    @Override
    public Funcionario getGenericPesquisaDomain() {
        funcionarioPesquisa.setNome(txtNomeFuncionarioPesquisa.getText());
        return funcionarioPesquisa;
    }

    @Override
    public FuncionarioBusiness getGenericBusiness() {
        return instanceFuncionarioBusiness();
    }

    @Override
    protected void setEntidade(Funcionario entidade) {
        funcionario = (Funcionario) entidade;
        txtNomeFuncionario.setText(funcionario.getNome());
        txtClt.setText(funcionario.getCarteiraTrabalho());
        txtCpf.setText(funcionario.getCpf());
        txtPis.setText(funcionario.getPis());
        txtRg.setText(funcionario.getRg());
        cmbCargo.setSelectedItem(funcionario.getCargo());
        txtDataContratacao.setText(formato.format(funcionario.getDataContratacao()));
        txtDataNascimento.setText(formato.format(funcionario.getDataNascimento()));
        txtDiaPagamento.setText("" + funcionario.getDiaPagamento());
        txtSalario.setLocale(Locale.getDefault());
        txtSalario.setText("" + funcionario.getSalario());
        contactJPanel.setTableValue(funcionario.getTelefoneContato());

    }
}
