/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CadastroMarcaProduto.java
 *
 * Created on 01/02/2013, 17:29:05
 */
package br.com.chronos.vetfaunasistema.view.marcaproduto;

import br.com.chronos.vetfaunasistema.view.generic.CrudView;
import br.com.chronos.vetfaunasistema.view.main.TelaPrincipal;
import javax.swing.JInternalFrame;

/**
 *
 * @author Fernando
 */
public class CadastroMarcaProduto extends JInternalFrame implements CrudView {

    private MarcaProdutoPanel marcaProdutoPanel;
    /** Creates new form CadastroMarcaProduto */
    public CadastroMarcaProduto(TelaPrincipal telaPrincipal) {
        marcaProdutoPanel = new MarcaProdutoPanel(this,telaPrincipal);
        initComponents();

    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = marcaProdutoPanel;

        setTitle("Cadastro de Marca de Produto");
        getContentPane().setLayout(null);
        getContentPane().add(pnlPrincipal);
        pnlPrincipal.setBounds(0, 0, 433, 390);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-443)/2, (screenSize.height-420)/2, 443, 420);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
// @Override
//    public void repaint(List<? extends GenericDomain> list, Class<?> clazz) {
//        Util.repaintComponents(list, clazz, marcaProdutoPanel.getRepaintComponets());
//    }
    public void setVisible(boolean valor) {
        if (valor) {
            marcaProdutoPanel.setVisible(valor);
        }
        super.setVisible(valor);
    }
}
