/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CadastroEstoque.java
 *
 * Created on 01/02/2013, 17:29:05
 */
package br.com.chronos.vetfaunasistema.view.estoque;

import br.com.chronos.vetfaunasistema.domain.GenericDomain;
import br.com.chronos.vetfaunasistema.domain.MarcaProduto;
import br.com.chronos.vetfaunasistema.utilitarios.util.Util;
import br.com.chronos.vetfaunasistema.view.component.Repaint;
import br.com.chronos.vetfaunasistema.view.generic.CrudView;
import java.util.List;
import javax.swing.JInternalFrame;

/**
 *
 * @author Fernando
 */
public class CadastroEstoque extends JInternalFrame implements CrudView {

    private EstoquePanel estoquePanel;

    /** Creates new form CadastroEstoque */
    public CadastroEstoque() {
        estoquePanel = new EstoquePanel(this);
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = estoquePanel;

        setTitle("Cadastro de Estoque");
        getContentPane().setLayout(null);
        getContentPane().add(pnlPrincipal);
        pnlPrincipal.setBounds(0, 0, 640, 660);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-653)/2, (screenSize.height-691)/2, 653, 691);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables

    public void setVisible(boolean valor) {
        if (valor) {
            estoquePanel.setVisible(valor);
        }
        super.setVisible(valor);
    }

//    @Override
//    public void repaint(List<? extends GenericDomain> list, Class<?> clazz) {
//        if (MarcaProduto.class.equals(clazz)) {
//            estoquePanel.preencheMarca();
//            estoquePanel.preencheMarcaPesquisa();
//        } else {
//            Util.repaintComponents(list, clazz, estoquePanel.getRepaintComponets());
//        }
//    }
}
