/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CadastroVendedor.java
 *
 * Created on 01/02/2013, 17:29:05
 */
package br.com.chronos.vetfaunasistema.view.vendedor;

import br.com.chronos.vetfaunasistema.domain.GenericDomain;
import br.com.chronos.vetfaunasistema.utilitarios.util.Util;
import br.com.chronos.vetfaunasistema.view.component.Repaint;
import br.com.chronos.vetfaunasistema.view.generic.CrudView;
import java.util.List;
import javax.swing.JInternalFrame;

/**
 *
 * @author Fernando
 */
public class CadastroVendedor extends JInternalFrame implements CrudView,Repaint {

    private VendedorPanel vendedorPanel;

    /** Creates new form CadastroVendedor */
    public CadastroVendedor() {
        vendedorPanel = new VendedorPanel(this);
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = vendedorPanel;

        setTitle("Cadastro de Vendedor");
        getContentPane().setLayout(null);
        getContentPane().add(pnlPrincipal);
        pnlPrincipal.setBounds(0, 0, 554, 550);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-567)/2, (screenSize.height-583)/2, 567, 583);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables

    public void setVisible(boolean valor) {
        if (valor) {
            vendedorPanel.setVisible(valor);
        }
        super.setVisible(valor);
    }

    @Override
    public void repaint(List<? extends GenericDomain> list, Class<?> clazz) {
       Util.repaintComponents(list, clazz, vendedorPanel.getRepaintComponets());
    }
}
