/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CadastroCategoriaProduto.java
 *
 * Created on 01/02/2013, 17:29:05
 */
package br.com.chronos.vetfaunasistema.view.categoriaproduto;

import br.com.chronos.vetfaunasistema.domain.GenericDomain;
import br.com.chronos.vetfaunasistema.view.component.Repaint;
import br.com.chronos.vetfaunasistema.view.generic.CrudView;
import br.com.chronos.vetfaunasistema.view.main.TelaPrincipal;
import java.util.List;
import javax.swing.JInternalFrame;

/**
 *
 * @author Fernando
 */
public class CadastroCategoriaProduto extends JInternalFrame implements CrudView{

    private CategoriaProdutoPanel categoriaProdutoPanel;

    /** Creates new form CadastroCategoriaProduto */
    public CadastroCategoriaProduto(TelaPrincipal telaPrincipal) {
        categoriaProdutoPanel = new CategoriaProdutoPanel(this,telaPrincipal);
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = categoriaProdutoPanel;

        setTitle("Cadastro de Categoria de Produto");
        getContentPane().setLayout(null);
        getContentPane().add(pnlPrincipal);
        pnlPrincipal.setBounds(0, 0, 433, 390);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-443)/2, (screenSize.height-420)/2, 443, 420);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables

    public void setVisible(boolean valor) {
        if (valor) {
            categoriaProdutoPanel.setVisible(valor);
        }
        super.setVisible(valor);
    }

   
   
}
