/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CadastroProduto.java
 *
 * Created on 01/02/2013, 17:29:05
 */
package br.com.chronos.vetfaunasistema.view.produto;

import br.com.chronos.vetfaunasistema.domain.GenericDomain;
import br.com.chronos.vetfaunasistema.domain.MarcaProduto;
import br.com.chronos.vetfaunasistema.utilitarios.util.Util;
import br.com.chronos.vetfaunasistema.view.component.Repaint;
import br.com.chronos.vetfaunasistema.view.generic.CrudView;
import java.util.List;
import javax.swing.JInternalFrame;

/**
 *
 * @author Fernando
 */
public class CadastroProduto extends JInternalFrame implements CrudView {

    private ProdutoPanel produtoPanel;

    /** Creates new form CadastroProduto */
    public CadastroProduto() {
        produtoPanel = new ProdutoPanel(this);
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = produtoPanel;

        setTitle("Cadastro de Produtos");
        getContentPane().setLayout(null);
        getContentPane().add(pnlPrincipal);
        pnlPrincipal.setBounds(0, 0, 640, 580);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-653)/2, (screenSize.height-610)/2, 653, 610);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables

    public void setVisible(boolean valor) {
        if (valor) {
            produtoPanel.setVisible(valor);
        }
        super.setVisible(valor);
    }

//    @Override
//    public void repaint(List<? extends GenericDomain> list, Class<?> clazz) {
//         if (MarcaProduto.class.equals(clazz)) {
//            produtoPanel.preencheMarca();
//            produtoPanel.preencheMarcaPesquisa();
//        } else {
//             Util.repaintComponents(list, clazz, produtoPanel.getRepaintComponets());
//         }
//    }
}
