/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CadastroCliente.java
 *
 * Created on 01/02/2013, 17:29:05
 */
package br.com.chronos.vetfaunasistema.view.cliente;

import br.com.chronos.vetfaunasistema.view.generic.CrudView;
import javax.swing.JInternalFrame;

/**
 *
 * @author Fernando
 */
public class CadastroCliente extends JInternalFrame implements CrudView {

    private ClientePanel clientePanel;

    /** Creates new form CadastroCliente */
    public CadastroCliente() {
        clientePanel = new ClientePanel(this);
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = clientePanel;

        setTitle("Cadastro de Clientes");
        getContentPane().setLayout(null);
        getContentPane().add(pnlPrincipal);
        pnlPrincipal.setBounds(0, 0, 590, 660);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-602)/2, (screenSize.height-689)/2, 602, 689);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables

    public void setVisible(boolean valor) {
        if (valor) {
            clientePanel.setVisible(valor);
        }
        super.setVisible(valor);
    }
}
