/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaPrincipal.java
 *
 * Created on 01/02/2013, 11:02:41
 */
package br.com.chronos.vetfaunasistema.view.main;

import br.com.chronos.vetfaunasistema.domain.GenericDomain;
import br.com.chronos.vetfaunasistema.view.cargo.CadastroCargo;
import br.com.chronos.vetfaunasistema.view.categoriaproduto.CadastroCategoriaProduto;
import br.com.chronos.vetfaunasistema.view.cliente.CadastroCliente;
import br.com.chronos.vetfaunasistema.view.component.Repaint;
import br.com.chronos.vetfaunasistema.view.estoque.CadastroEstoque;
import br.com.chronos.vetfaunasistema.view.funcionario.CadastroFuncionario;
import br.com.chronos.vetfaunasistema.view.fornecedor.CadastroFornecedor;
import br.com.chronos.vetfaunasistema.view.marcaproduto.CadastroMarcaProduto;
import br.com.chronos.vetfaunasistema.view.produto.CadastroProduto;
import br.com.chronos.vetfaunasistema.view.vacina.CadastroVacina;
import br.com.chronos.vetfaunasistema.view.vendedor.CadastroVendedor;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JRootPane;

/**
 *
 * @author Fernando
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /** Creates new form TelaPrincipal */
    public TelaPrincipal() {
        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setUndecorated(true);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        jLabel1.setIcon(new javax.swing.ImageIcon("pictures\\icones\\user.png")); // NOI18N
        lblProdutos.setIcon(new javax.swing.ImageIcon("pictures\\icones\\produtos1.png")); // NOI18N
        lblEstoque.setIcon(new javax.swing.ImageIcon("pictures\\icones\\estoque2.png")); // NOI18N
        lblCliente.setIcon(new javax.swing.ImageIcon("pictures\\icones\\Cliente.png")); // NOI18N
        lblLogo.setIcon(new javax.swing.ImageIcon("pictures\\Vet_Fauna_Logomarca.jpg")); // NOI18N
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        lblLogo.setLocation(screenSize.width-lblLogo.getSize().width-10, 10);
    }

    public void repaintAll(List<? extends GenericDomain> list,Class<?> clazz){
        for (JInternalFrame jif : dtpFramePrincipal.getAllFrames()) {
            for (Object o : jif.getContentPane().getComponents()) {
                if(Repaint.class.isInstance(o)){
                    Repaint r = (Repaint) o;
                    r.repaint(list, clazz);
                }
            }
        }
         
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        dtpFramePrincipal = new br.com.chronos.vetfaunasistema.view.component.desktoppanel.DesktopPaneFramePrincipal();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblProdutos = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblEstoque = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        mnuProduto = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        mnuMarcaProduto = new javax.swing.JMenuItem();
        mnuCategoriaProduto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dtpFramePrincipal.setBackground(new java.awt.Color(255, 255, 255));
        dtpFramePrincipal.setDesktopManager(null);

        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jLabel1.setBounds(17, 10, 50, 60);
        dtpFramePrincipal.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Funcionários");
        jLabel2.setBounds(0, 70, 80, 14);
        dtpFramePrincipal.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblProdutos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProdutos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProdutosMouseClicked(evt);
            }
        });
        lblProdutos.setBounds(17, 100, 50, 60);
        dtpFramePrincipal.add(lblProdutos, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Produtos");
        jLabel4.setBounds(0, 155, 80, 14);
        dtpFramePrincipal.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblEstoque.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEstoqueMouseClicked(evt);
            }
        });
        lblEstoque.setBounds(17, 190, 48, 48);
        dtpFramePrincipal.add(lblEstoque, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Estoque");
        jLabel5.setBounds(0, 240, 80, 14);
        dtpFramePrincipal.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lblLogo.setBounds(432, 10, 200, 0);
        dtpFramePrincipal.add(lblLogo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClienteMouseClicked(evt);
            }
        });
        lblCliente.setBounds(20, 275, 50, 48);
        dtpFramePrincipal.add(lblCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Clientes");
        jLabel6.setBounds(0, 325, 80, 14);
        dtpFramePrincipal.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        fileMenu.setMnemonic('f');
        fileMenu.setText("Arquivo");

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Cadastros");

        jMenu2.setText("Empresa");

        jMenuItem7.setText("Cargos");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Funcionários");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        editMenu.add(jMenu2);

        jMenuItem6.setText("Vacinas");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        editMenu.add(jMenuItem6);

        jMenu1.setText("Compras");

        jMenuItem3.setText("Vendedor");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem2.setText("Fornecedor");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        editMenu.add(jMenu1);

        mnuProduto.setText("Produtos");

        jMenuItem4.setText("Produto");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        mnuProduto.add(jMenuItem4);

        jMenuItem5.setText("Estoque");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        mnuProduto.add(jMenuItem5);

        mnuMarcaProduto.setText("Marca de Produto");
        mnuMarcaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMarcaProdutoActionPerformed(evt);
            }
        });
        mnuProduto.add(mnuMarcaProduto);

        mnuCategoriaProduto.setText("Categoria de Produto");
        mnuCategoriaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCategoriaProdutoActionPerformed(evt);
            }
        });
        mnuProduto.add(mnuCategoriaProduto);

        editMenu.add(mnuProduto);

        menuBar.add(editMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dtpFramePrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(dtpFramePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
    openCadastroFuncionario();
}//GEN-LAST:event_jLabel1MouseClicked

private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
    openCadastroFornecedor();
}//GEN-LAST:event_jMenuItem2ActionPerformed

private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
    openCadastroVendedor();
}//GEN-LAST:event_jMenuItem3ActionPerformed

private void mnuMarcaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMarcaProdutoActionPerformed
    openCadastroMarcaProduto();
}//GEN-LAST:event_mnuMarcaProdutoActionPerformed

private void mnuCategoriaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCategoriaProdutoActionPerformed
    openCadastroCategoriaProduto();
}//GEN-LAST:event_mnuCategoriaProdutoActionPerformed

private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
    openCadastroProduto();
}//GEN-LAST:event_jMenuItem4ActionPerformed

private void lblProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProdutosMouseClicked
    openCadastroProduto();
}//GEN-LAST:event_lblProdutosMouseClicked

private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
    openCadastroEstoque();
}//GEN-LAST:event_jMenuItem5ActionPerformed

private void lblEstoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEstoqueMouseClicked
    openCadastroEstoque();
}//GEN-LAST:event_lblEstoqueMouseClicked

private void lblClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClienteMouseClicked
    openCadastroCliente();
}//GEN-LAST:event_lblClienteMouseClicked

private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    openCadastroFuncionario();
}//GEN-LAST:event_jMenuItem1ActionPerformed

private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
    openCadastroVacina();
}//GEN-LAST:event_jMenuItem6ActionPerformed

private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
    openCadastroCargo();
}//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//        Begin b = new Begin();
//        b.
//        java.awt.EventQueue.invokeLater(b);
//        new Thread(b).start();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                TelaPrincipal t = new TelaPrincipal();

                t.setVisible(true);
            }
        });
//        b.runThread(false);
    }

    public void openCadastroFuncionario() {
        if (cadastroFuncionario == null) {
            cadastroFuncionario = new CadastroFuncionario();
            dtpFramePrincipal.add(cadastroFuncionario);
        }
        cadastroFuncionario.setVisible(true);
    }
    public void openCadastroCliente() {
        if (cadastroCliente == null) {
            cadastroCliente = new CadastroCliente();
            dtpFramePrincipal.add(cadastroCliente);
        }
        cadastroCliente.setVisible(true);
    }

    public void openCadastroFornecedor() {
        if (cadastroFornecedor == null) {
            cadastroFornecedor = new CadastroFornecedor(this);
            dtpFramePrincipal.add(cadastroFornecedor);
        }
        cadastroFornecedor.setVisible(true);
    }
    public void openCadastroEstoque() {
        if (cadastroEstoque == null) {
            cadastroEstoque = new CadastroEstoque();
            dtpFramePrincipal.add(cadastroEstoque);
        }
        cadastroEstoque.setVisible(true);
        cadastroEstoque.requestFocus();
    }
    public void openCadastroVacina() {
        if (cadastroVacina == null) {
            cadastroVacina = new CadastroVacina(this);
            dtpFramePrincipal.add(cadastroVacina);
        }
        cadastroVacina.setVisible(true);
        cadastroVacina.requestFocus();
    }
    public void openCadastroCargo() {
        if (cadastroCargo == null) {
            cadastroCargo = new CadastroCargo(this);
            dtpFramePrincipal.add(cadastroCargo);
        }
        cadastroCargo.setVisible(true);
        cadastroCargo.requestFocus();
    }

    public void openCadastroVendedor() {
        if (cadastroVendedor == null) {
            cadastroVendedor = new CadastroVendedor();
            dtpFramePrincipal.add(cadastroVendedor);
        }
        cadastroVendedor.setVisible(true);
    }

    public void openCadastroMarcaProduto() {
        if (cadastroMarcaProduto == null) {
            cadastroMarcaProduto = new CadastroMarcaProduto(this);
            dtpFramePrincipal.add(cadastroMarcaProduto);
        }
        cadastroMarcaProduto.setVisible(true);
    }

    public void openCadastroCategoriaProduto() {
        if (cadastroCategoriaProduto == null) {
            cadastroCategoriaProduto = new CadastroCategoriaProduto(this);
            dtpFramePrincipal.add(cadastroCategoriaProduto);
        }
        cadastroCategoriaProduto.setVisible(true);
    }

    public void openCadastroProduto() {
        if (cadastroProduto == null) {
            cadastroProduto = new CadastroProduto();
            dtpFramePrincipal.add(cadastroProduto);
        }
        cadastroProduto.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dtpFramePrincipal;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblEstoque;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblProdutos;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mnuCategoriaProduto;
    private javax.swing.JMenuItem mnuMarcaProduto;
    private javax.swing.JMenu mnuProduto;
    // End of variables declaration//GEN-END:variables
    private CadastroFornecedor cadastroFornecedor;
    private CadastroFuncionario cadastroFuncionario;
    private CadastroVendedor cadastroVendedor;
    private CadastroMarcaProduto cadastroMarcaProduto;
    private CadastroCategoriaProduto cadastroCategoriaProduto;
    private CadastroProduto cadastroProduto;
    private CadastroCliente cadastroCliente;
    private CadastroVacina cadastroVacina;
    private CadastroCargo cadastroCargo;
    private CadastroEstoque cadastroEstoque;
}
